# Data Analytics with numpy

## numpy arrays

In [1]:
import numpy as np

In [2]:
lst = [4,5,6]

In [3]:
lst

[4, 5, 6]

In [7]:
np_vec = np.array(lst)

In [9]:
nested_lst = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
nested_lst

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np_matrix = np.array(nested_lst)
np_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### List comprehension

In [13]:
[x**2 for x in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [17]:
lst_comp = []
for x in range(10):
    lst_comp.append(x**2)
lst_comp

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [18]:
np.array([x**2 for x in range(10)])

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

## Built-in methods

In [23]:
%timeit np.arange(0,10)

1.51 µs ± 167 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [25]:
%timeit np.array(range(10))

11.4 µs ± 1.43 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [27]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [32]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [33]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [35]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
np.matmul(np.eye(3), np_matrix)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

### linspace

In [47]:
np.linspace(0,1,1001)

array([0.   , 0.001, 0.002, ..., 0.998, 0.999, 1.   ])

### Random numbers

In [49]:
rand_vec = np.random.rand(100)
rand_vec

array([0.20661751, 0.26107111, 0.32679536, 0.8973953 , 0.16532297,
       0.31551436, 0.69262575, 0.95015723, 0.32116605, 0.38707819,
       0.57480282, 0.77444506, 0.89920125, 0.93144129, 0.47885977,
       0.74571181, 0.90222897, 0.05700552, 0.93491125, 0.3920269 ,
       0.28454949, 0.15041341, 0.63458055, 0.84672628, 0.78339807,
       0.60741092, 0.95278827, 0.14851578, 0.59284235, 0.8427188 ,
       0.17394914, 0.10276585, 0.80216989, 0.75943014, 0.71939445,
       0.8317102 , 0.72255568, 0.81683007, 0.19679122, 0.2393903 ,
       0.5178586 , 0.0695761 , 0.8005293 , 0.32970117, 0.49627259,
       0.6560411 , 0.28718364, 0.91233142, 0.38856644, 0.11098738,
       0.2251291 , 0.65889896, 0.99254031, 0.69896831, 0.73659608,
       0.96455426, 0.84277699, 0.00140586, 0.66471456, 0.1867221 ,
       0.91167096, 0.45307161, 0.02714175, 0.93118381, 0.11107083,
       0.54198217, 0.56908781, 0.59004465, 0.94360958, 0.5607096 ,
       0.71765092, 0.69738715, 0.02998108, 0.13128749, 0.08080

In [51]:
rand_matrix = np.random.rand(5,5)
rand_matrix

array([[0.11817959, 0.10906681, 0.27710602, 0.07181353, 0.23210342],
       [0.19250313, 0.24467819, 0.26107776, 0.45769097, 0.83236248],
       [0.57925461, 0.77557612, 0.25317224, 0.78756262, 0.18763294],
       [0.78748521, 0.46325834, 0.22614021, 0.84037425, 0.88988495],
       [0.31445063, 0.37206136, 0.52948596, 0.55706232, 0.23830211]])

In [56]:
5+5*np.random.randn(100)

array([ 0.2149781 ,  3.66282257,  1.66946056, 11.90099614,  3.68801594,
        5.62274777, 13.18936745, 11.91516423, 11.13019082,  7.73908541,
        4.7709581 ,  6.58547578,  6.35880031,  2.6831995 ,  6.34262971,
        0.41640509,  8.23282811,  5.29983586,  5.26667136,  6.79318694,
        6.47933259, 13.57032784,  2.08524344,  6.24003825,  5.60666525,
        7.67367252,  6.98062989,  2.07477818, 13.64570046, -0.40411961,
        1.48120129,  6.94683114, 10.13221522,  1.89225059,  1.93590464,
       -0.07760342, 13.37089278,  3.08812192, 12.55740502,  3.24665623,
        6.35467972,  1.74990378,  3.6276472 ,  1.53098709, 12.26368711,
       -0.05791893,  0.40930858,  7.64531727,  2.37221901, 13.96468582,
       15.644938  ,  6.72447011, 10.67674336,  6.64000787,  0.16267961,
        6.09148097, -1.82815829,  5.3588438 ,  3.93294319,  4.40773922,
        2.56000384, 13.24345915,  4.70317594, 13.18860152,  9.13135976,
        4.28724881,  0.73119451,  1.70885744,  3.55218457,  7.09

In [58]:
np.random.randint(1,100,100)

array([93, 31, 63, 55, 30, 50, 65, 10, 33, 16, 50, 98, 89, 63, 78, 97, 57,
       63, 17, 14, 84, 55, 12, 46, 60, 74, 36, 64, 18, 50, 16,  8, 58, 25,
       74, 86, 91, 84, 60, 25, 63, 84, 93,  6, 93, 72, 40, 63, 98, 31, 71,
       80, 15, 25, 75, 90, 16, 93, 23, 78, 90, 82, 49, 99, 90, 79, 83, 34,
       68, 39, 97, 16,  1,  1, 57, 79,  5, 25, 60, 69, 91, 72, 68, 36,  4,
       44,  3, 88, 42, 28, 88, 96, 18, 34, 88, 99, 84, 53, 69, 92])

### Numpy methods

In [59]:
np_vec

array([4, 5, 6])

In [60]:
np_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
np_matrix.size

9

In [66]:
np_vec.size

3

In [67]:
np_matrix.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [68]:
np_matrix.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [70]:
np_matrix.reshape(9,-1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [71]:
np_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
np_matrix.max()

9

In [74]:
np_matrix.min()

1

In [75]:
np_matrix.argmax()

8

In [76]:
np_matrix.argmin()

0

In [79]:
np_matrix.shape

(3, 3)

In [86]:
np_vec.shape

(3,)

In [87]:
np_matrix.dtype

dtype('int64')